portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name='home'),
    path('journey/', views.journey, name='journey'),
    path('toolbox/', views.toolbox, name='toolbox'),
    path('projects/', views.projects, name='projects'),
    path('experience/', views.experience, name='experience'),
]

web_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls', namespace='portfolio')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models
from PIL import Image
from django.core.files.storage import default_storage
from io import BytesIO

class TagCategory(models.Model):
    name        = models.CharField(max_length=100)
    hierarchy   = models.IntegerField(null=True, unique=True)
    def __str__(self):
        return self.name


class Tag(models.Model):
    name        = models.CharField(max_length=100)
    tagcategory = models.ForeignKey(TagCategory, related_name='tag', 
        on_delete=models.DO_NOTHING, null=True, blank=True)
    icon_class  = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return self.name


class Project(models.Model):
    name            = models.CharField(max_length=100)
    content         = models.TextField()
    date_created    = models.DateField()
    url             = models.URLField(max_length=200, null=True, blank=True)
    github_url      = models.URLField(max_length=200, null=True, blank=True)
    image           = models.ImageField(upload_to='images', null=True, blank=True)
    tags            = models.ManyToManyField(Tag, related_name='tag',
        through='Project_Tag', 
        )

    # def save(self, *args, **kwargs):
    #     """resize image on upload"""
    #     super().save(*args, **kwargs)
    #     memfile = BytesIO()
    #     img = Image.open(self.image)
    #     if img.height > 800 or img.width > 800:
    #         output_size = (400, 400)
    #         img.thumbnail(output_size, Image.ANTIALIAS)
    #         img.save(memfile)
    #         default_storage.save(self.image.name, memfile)
    #         memfile.close()
    #         img.close()

    def __str__(self):
        return self.name


class Project_Tag(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    tag     = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.project.name} ' - ' {self.tag.name}"


class Intro(models.Model):
    #the welcome text onsite
    content   = models.TextField()
    hierarchy = models.IntegerField(null=True, unique=True)

    def __str__(self):
        return f"{self.hierarchy} ' - ' {self.content}"

class RoleDescription(models.Model):
    #brief strapline under my name
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content


class CVRole(models.Model):
    title      = models.CharField(max_length=100)
    company    = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date   = models.DateField(null=True, blank=True)
    overview   = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.title}"


class CVRoleItem(models.Model):
    cv_role = models.ForeignKey(CVRole, on_delete=models.CASCADE, related_name='roleitems')
    content = models.TextField()


class Journey(models.Model):
    content = models.TextField()

portfolio/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Prefetch
from portfolio.models import CVRole, Intro, Journey, TagCategory, Project, Project_Tag

# Create your views here.

def home(request):
    intro    = Intro.objects.all().order_by('hierarchy')

    context = {
        'intro':intro,
    }
    return render(request, 'portfolio/main/index.html', context)


def journey(request):
    journey    = Journey.objects.all()

    context = {
        'journey':journey,
    }
    return render(request, 'portfolio/main/journey.html', context)


def toolbox(request):
    tagcats  = TagCategory.objects.all().prefetch_related('tag').order_by('hierarchy')

    context = {
        'tagcats':tagcats,
    }
    return render(request, 'portfolio/main/toolbox.html', context)


def projects(request):
    projects = Project.objects.all().prefetch_related('tags').order_by('-date_created')

    context = {
        'projects':projects,
    }
    return render(request, 'portfolio/main/projects.html', context)


def experience(request):
    cvrole   = CVRole.objects.all().prefetch_related('roleitems').order_by('-start_date')

    context = {
        'cvrole':cvrole,
    }
    return render(request, 'portfolio/main/experience.html', context)


    

templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- CDN Fonts/Icons/Bootstrap -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
  
  
  <!-- Static CSS  -->
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  
  <title>Charlie Avery</title>
</head>

<body class="bg-gray-8 d-flex flex-column min-vh-100">
  
{% include 'portfolio/navbar.html' %}

<main class="min-vh-90">
{% block content %}{% endblock content %}
</main>


<!--Footer-->
<footer class="mt-auto p-5 bg-dark text-light text-center position-relative">
  <p class="lead">Charlie Avery 2021</p>
  <a href="#" class="position-absolute bottom-0 end-0 p-5">
    <i class="bi bi-arrow-up-circle h1"></i>
  </a>
</footer>


<script 
src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
crossorigin="anonymous">
</script>

</body>
</html>

templates/portfolio/main/contact_modal.html
<div class="modal fade" id="contact" tabindex="-1" aria-labelledby="enrollLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="enrollLabel">Contact Me</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="lead">This is an example pop-up. Please contact me via my LinkedIn.</p>
          <form>
            <div class="mb-3">
              <label for="first-name" class="col-form-label">
                First Name:
              </label>
              <input type="text" class="form-control" id="first-name" />
            </div>
            <div class="mb-3">
              <label for="last-name" class="col-form-label">Last Name:</label>
              <input type="text" class="form-control" id="last-name" />
            </div>
            <div class="mb-3">
              <label for="email" class="col-form-label">Email:</label>
              <input type="email" class="form-control" id="email" />
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
            Close
          </button>
          <button type="button" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>
  </div>

templates/portfolio/main/cv.html
<section class="bg-gray-8 text-light p-5" id="experience">
	<div class="container">
		<h1 class="mb-5 text-center">Experience</h1>

		{% for role in cvrole %}
		<div class="container ms-5 pt-4">
			<h5 class="mb-3">
				<strong>{{role.title}}, {{role.company}}:</strong> 
				{{ role.start_date|date:"M Y" }} - 
				{% if role.end_date %}
					{{ role.end_date|date:"M Y" }}
				{% else %}
					Present
				{% endif %}
			</h5>
			{% if role.overview %}
				<p>{{ role.overview }}</p>
			{% endif %}
			<ul>
				{% for roleitem in role.roleitems.all %}
					<li>{{roleitem.content}}</li>
				{% endfor %}
			</ul>
		</div>
		{% endfor %}
	</div>
</section>
  

templates/portfolio/main/experience.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}


<section class="bg-gray-8 text-light p-5" id="experience">
	<div class="container">
		<h1 class="mb-5 text-center">Experience</h1>

		{% for role in cvrole %}
		<div class="container ms-5 pt-4">
			<h5 class="mb-3">
				<strong>{{role.title}}, {{role.company}}:</strong> 
				{{ role.start_date|date:"M Y" }} - 
				{% if role.end_date %}
					{{ role.end_date|date:"M Y" }}
				{% else %}
					Present
				{% endif %}
			</h5>
			{% if role.overview %}
				<p>{{ role.overview }}</p>
			{% endif %}
			<ul>
				{% for roleitem in role.roleitems.all %}
					<li>{{roleitem.content}}</li>
				{% endfor %}
			</ul>
		</div>
		{% endfor %}
	</div>
</section>
  

{% endblock content %}

templates/portfolio/main/index.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<!-- Intro Section -->
<section class="bg-gray-8 text-light p-5 text-center text-md-start" id="background">
  <div class="container">
    <div class="d-md-flex align-items-center justify-content-between">
      <div class="col mb-5 mx-1">
        <h1>Charlie Avery </h1>
        <h1 class="text-muted">Data Analytics Developer</h1>
        {% for i in intro %}
          <p class="lead my-3">
            {{ i.content | safe }}
          </p>
        {% endfor %}      
        <button class="btn btn-success btn-lg" data-bs-toggle="modal" data-bs-target="#contact">
          Get In Touch!
        </button>
      </div>
      <div class="col">
        <img class="mx-auto d-none d-md-block" src="{% static 'images/charlie.jfif' %}" alt="">
      </div>
    </div>
  </div>
</section>







<!-- Contact Modal -->
{% include 'portfolio/main/contact_modal.html' %}


{% endblock content %}

templates/portfolio/main/journey.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<!-- Toolbox -->
<section class="bg-gray-8 text-light p-5" id="toolbox">
  <div class="container text-center">
    <div class="h1">My Journey (so far)</div>
  </div>
</section>

<section>
  <div class="container text-light">
    {% for j in journey %}
      <p class="lead my-3">
        {{ j.content | safe }}
      </p>
    {% endfor %}
  </div>   
</section>



{% endblock content %}

templates/portfolio/main/projects.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}


<section class="bg-gray-8 text-light p-5" id="projects">
  <div class="container text-center">
    <div class="h1 mb-5">Projects</div>
    <p>
      These are some recent projects I have created. They are related to areas that interest me, using technologies I want to develop skills in. 
    </p>
  </div>
</section>


<section class="bg-gray-8 p-5">
  <div class="container">
    <div class="row justify-content-center g-5">
      {% for p in projects %}
      <div class="col-12 col-lg-6">
        <div class="card bg-dark text-light text-center h-100">
          {% if p.image %}
            <a href="{{p.url}}"><img src="{{ p.image.url }}" class="card-img-top" width="400" 
              height="400" ></a>
          {% endif %}
          <div class="card-body my-2">
            <h3 class="card-title">{{ p.name }}</h3>
            <p class="card-text">
              {{ p.content | safe }}
            </p>
          </div>
          <div class="card-footer bg-transparent border-0">
          
            {% for tag in p.tags.all %}
              <span class="badge rounded-pill bg-secondary m-1">{{ tag.name }}</span>
            {% endfor %}
          </div>

          <div class="card-footer">
            <a href="{{p.url}}" class="card-link">Project</a>
            <a href="{{p.github_url}}" class="card-link">Github</a>
          </div>

        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>


{% endblock content %}

templates/portfolio/main/projects_div.html
<section class="bg-dark p-5">
  <div class="container">
    <div class="row justify-content-center g-5">
      {% for p in projects %}
      <div class="col-12 col-lg-6">
        <div class="card bg-gray-8 text-light text-center h-100">
          {% if p.image %}
            <a href="{{p.url}}"><img src="{{ p.image.url }}" class="card-img-top" width="400" 
              height="400" ></a>
          {% endif %}
          <div class="card-body my-2">
            <h3 class="card-title">{{ p.name }}</h3>
            <p class="card-text">
              {{ p.content | safe }}
            </p>
          </div>
          <div class="card-footer bg-transparent border-0">
          
            {% for tag in p.tags.all %}
              <span class="badge rounded-pill bg-secondary m-1">{{ tag.name }}</span>
            {% endfor %}
          </div>

          <div class="card-footer">
            <a href="{{p.url}}" class="card-link">Project</a>
            <a href="{{p.github_url}}" class="card-link">Github</a>
          </div>

        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

templates/portfolio/main/toolbox.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<!-- Toolbox -->
<section class="bg-gray-8 text-light p-5" id="toolbox">
  <div class="container text-center">
    <div class="h1">My Toolbox</div>
  </div>
</section>


{% for tagcat in tagcats %}
  <section class="bg-gray-8 pb-5 text-center" id=''>
    <div class="container">
      <div class="h2 text-light mb-5">{{ tagcat.name }}</div>
      <div class="row justify-content-center g-4">
        
        {% for tag in tagcat.tag.all %}
        <div class="col-sm-6 col-md-3 col-lg">
          <div class="card bg-dark text-light h-100">
            <div class="card-body">
              <i class="{{ tag.icon_class }}"></i>
              <h4 class="my-3">{{ tag.name }}</h4>
            </div>
          </div>
        </div>
        {% endfor %}
        
      </div>
    </div>
  </section>
{% endfor %}


{% endblock content %}

templates/portfolio/main/tools_div.html
{% for tagcat in tagcats %}
  <section class="bg-gray-8 pb-5 text-center" id=''>
    <div class="container">
      <div class="h2 text-light mb-5">{{ tagcat.name }}</div>
      <div class="row justify-content-center g-4">
        
        {% for tag in tagcat.tag.all %}
        <div class="col-sm-6 col-md-3 col-lg">
          <div class="card bg-dark text-light h-100">
            <div class="card-body">
              <i class="{{ tag.icon_class }}"></i>
              <h4 class="my-3">{{ tag.name }}</h4>
            </div>
          </div>
        </div>
        {% endfor %}
        
      </div>
    </div>
  </section>
{% endfor %}

templates/portfolio/navbar.html
<nav class="navbar navbar-expand-lg fixed-top bg-dark navbar-dark py-3">
  <div class="container">
    <a href="{% url 'portfolio:home' %}" class="navbar-brand text-decoration-none">
      <i class="bi bi-terminal"></i>
      <i class="bi bi-code-square"></i>
      <i class="bi bi-graph-up"></i>
      <i class="bi bi-server"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navmenu">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="https://www.linkedin.com/in/charlie-avery-7b4a2a7b/" target="_blank" class="nav-link">
            <i class="bi bi-linkedin"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="https://github.com/charliewhu/" target="_blank" class="nav-link">
            <i class="bi bi-github"></i>
            
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'portfolio:journey' %}" class="nav-link">My Journey</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'portfolio:toolbox' %}" class="nav-link">Toolbox</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'portfolio:projects' %}" class="nav-link">Projects</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'portfolio:experience' %}" class="nav-link">Experience</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>